tools:
  - name: "Prometheus"
    latestVersionEndpoint: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
    remoteVersionEndpoint: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
    remoteVersionJSONKey: "tag_name"
    latestVersionJSONKey: "tag_name"
  - name: "Grafana"
    latestVersionEndpoint: "https://api.github.com/repos/grafana/grafana/releases/latest"
    remoteVersionEndpoint: "https://api.github.com/repos/grafana/grafana/releases/latest"
    remoteVersionJSONKey: "tag_name"
    latestVersionJSONKey: "tag_name"
