latestVersionEndpoints:
  - name: grafana
    url: 'https://api.github.com/repos/grafana/grafana/releases/latest'
    JSONKey: 'tag_name'

myEndpoints:
  - name: Grafana
    url: 'https://grafana-fxi-001-eastus2-prod.tools.fxi-svc.az.fxei.fedex.com/api/health'
    JSONKEY: 'data.key'
    latestEndpointName: 'grafana'
# fetchInterval: 10 # defined in minutes
# tools:
#   - name: 'Prometheus2'
#     latestVersionEndpoint: 'https://prometheus-fxi-001-nonprod.tools.fxi-svc.az.fxei.fedex.com/api/v1/status/buildinfo'
#     latestVersionJSONKey: 'data.version'
#     myVersionEndpoint: 'https://api.github.com/repos/prometheus/prometheus/releases/latest'
#     myVersionJSONKey: 'tag_name'
#     # currentVersion: 'v2.48.1'
#     # comment: 'Blocked by vulnerability in latest version.'
#   - name: 'Prometheus'
#     latestVersionEndpoint: 'https://api.github.com/repos/prometheus/prometheus/releases/latest'
#     latestVersionJSONKey: 'tag_name'
#     # myVersionEndpoint: 'https://api.github.com/repos/prometheus/prometheus/releases/latest'
#     # myVersionJSONKey: 'tag_name'
#     currentVersion: 'v2.48.1'
#     comment: 'Blocked by vulnerability in latest version.'
#   - name: 'Grafana'
#     latestVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     latestVersionJSONKey: 'tag_name'
#     myVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     myVersionJSONKey: 'tag_name'
#   - name: 'Grafana2'
#     latestVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     latestVersionJSONKey: 'tag_name'
#     myVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     myVersionJSONKey: 'tag_name'
#   - name: 'Grafana3'
#     latestVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     latestVersionJSONKey: 'tag_name'
#     myVersionEndpoint: 'https://api.github.com/repos/grafana/grafana/releases/latest'
#     myVersionJSONKey: 'tag_name'
